rabbitmq:
  addresses: 47.96.226.188:5672
  username: root
  password: subat-dev
  virtual-host: impl
datasources:
  default:
    url: jdbc:mysql://47.96.226.188:3306/uchur
    username: admin
    password: admin-dev
