micronaut:
  application:
    name: address
    default-charset: UTF-8
  router:
    static-resources:
      spdoc:
        paths: classpath:spdoc/
        mapping: /spdoc/**
datasources:
  default:
    url: jdbc:mysql://localhost:3306/subat_new
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL
    connection-timeout: 60000
    max-lifetime: 540000
    idle-timeout: 500000
    maximum-pool-size: 20
    minimum-idle: 10
jpa:
  default:
    properties:
      hibernate:
        physical_naming_strategy: 'cn.subat.impl.common.util.ImplCamelToSnake'
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: update
        show_sql: true
rabbitmq:
  addresses: localhost:5672
  username: guest
  password: guest
  virtual-host: impl
  connection-timeout: 10000
  connection-retry:
    initial-interval: 1000
    multiplier: 2
    max-interval: 10000
    max-attempts: 10
jackson:
  property-naming-strategy: SNAKE_CASE
spdoc:
  path: api.yaml
  url: http://localhost:8500/api/
